# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{composite}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Menke"]
  s.date = %q{2009-09-22}
  s.default_executable = %q{composite}
  s.description = %q{Compose rails applications using several smaller rails applicatons}
  s.email = %q{simon@mrhenry.be}
  s.executables = ["composite"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/composite",
     "composite.gemspec",
     "lib/composite.rb",
     "lib/composite.rb",
     "lib/composite/app.rb",
     "lib/composite/app.rb",
     "lib/composite/automagic.rb",
     "lib/composite/automagic.rb",
     "lib/composite/cache.rb",
     "lib/composite/cache.rb",
     "lib/composite/dependency_resolver.rb",
     "lib/composite/dependency_resolver.rb",
     "lib/composite/environment.rb",
     "lib/composite/environment.rb",
     "lib/composite/extender.rb",
     "lib/composite/extender.rb",
     "lib/composite/linker.rb",
     "lib/composite/linker.rb",
     "lib/composite/loader.rb",
     "lib/composite/loader.rb",
     "lib/composite/rails_extentions/boot.rb",
     "lib/composite/rails_extentions/boot.rb",
     "lib/composite/rails_extentions/configuration.rb",
     "lib/composite/rails_extentions/configuration.rb",
     "lib/composite/rails_extentions/initializer.rb",
     "lib/composite/rails_extentions/initializer.rb",
     "lib/composite/rails_extentions/migrations.rb",
     "lib/composite/rails_extentions/migrations.rb",
     "lib/composite/rubygems_extentions/specification.rb",
     "lib/composite/rubygems_extentions/specification.rb",
     "lib/composite/template.rb",
     "lib/composite/utils/composite_methods.rb",
     "lib/composite/utils/composite_methods.rb",
     "lib/composite/validator.rb",
     "lib/composite/validator.rb",
     "lib/rubygems_plugin.rb",
     "lib/rubygems_plugin.rb",
     "templates/composite.yml",
     "templates/jeweler.rake",
     "templates/preinitializer.rb",
     "test/composite_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/simonmenke/composite}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Make composite rails applications}
  s.test_files = [
    "test/composite_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<snapshots>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<snapshots>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<snapshots>, [">= 0"])
  end
end
